image: Visual Studio 2019

configuration: Release

cache:
- packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
- '%LocalAppData%\NuGet\v3-cache' # NuGet v3

before_build:
- nuget restore

build:
  project: DiztinGUIsh.sln
  verbosity: minimal

after_build:
- create-final-zip.bat
  
artifacts:
- path: DiztinGUIsh\bin\Release\
  name: DiztinGUIsh

deploy:
- provider: GitHub
  auth_token:
    secure: H/F8/J5vKZm7RssnY3ZR4i0mk/3mxQ+6RqNF1lYCtrhMQgMSiBbzO5MaVAZD0dXt
  artifact: diztinguish.zip
  draft: false
  prerelease: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true       # deploy on tag push only