# TODO: make sure support files in dist/ are copied into the final release folder still, final dir structure mirrors original build process
 # TODO: add nuget package cache back in

name: .NET 5 Win Desktop

on: [ push, pull_request ]

jobs:

  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Build
        run: dotnet build
        
      - name: Test
        run: dotnet test
  
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: DiztinGUIsh
          path: DiztinGUIsh\bin\Release
